# Generated by Django 5.1.4 on 2025-01-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('task_status', models.CharField(choices=[('TO', 'TO DO'), ('DO', 'DOING'), ('DN', 'DONE')], default='TO', max_length=10)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
