# Generated by Django 5.1.4 on 2025-03-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='url_code',
            field=models.CharField(default='4b2328d4b01589364b231dc3ffd6f51ea4e9ed94610fcb5f6357', max_length=60),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_token',
            field=models.CharField(default='9af52c2b71bc', max_length=8),
        ),
    ]
