# Generated by Django 5.1.4 on 2025-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_otptoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_token',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='url_code',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=60, null=True),
        ),
    ]
