# Generated by Django 5.1.4 on 2025-07-22 18:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default_nsg6f7.jpg', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='profile_pic/'),
        ),
    ]
