# Generated by Django 5.1.4 on 2025-07-24 19:50

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='profile_pic/'),
        ),
    ]
