# Generated by Django 5.1.4 on 2025-03-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
