# Generated by Django 5.1.4 on 2025-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_otptoken_url_code_alter_otptoken_otp_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='otp_expire_at',
        ),
        migrations.AddField(
            model_name='otptoken',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_token',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='url_code',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
