# Generated by Django 5.1.4 on 2025-03-20 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_otptoken_otp_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
